version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: gunicorn ecommerce_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    command: celery -A ecommerce_api worker -l INFO
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
      - db

  celery-beat:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    command: celery -A ecommerce_api beat -l INFO
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
      - db
      - celery

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
